# -*- coding: utf-8 -*-
"""letter_frequency_.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bxMRYPrgXP1GAc1ZyUjXt_OrGRmEzv-d
"""

import matplotlib.pyplot as plt

def getFreq(text):
    text = text.lower()

    letters= sorted([char for char in set(text) if char.isalpha()])

    letter_dict = dict.fromkeys(letters, 0)

    for char in text:
        if char in letter_dict:
            letter_dict[char] +=1
    return letter_dict, letters

def plot_letter_frequency(letter_dict, letters, language, total_chars):
    frequencies = [100* letter_dict[letter] / total_chars for letter in letters]
    plt.bar(letters, frequencies)
    plt.xlabel('Letter')
    plt.ylabel('Frequency')
    plt.title(f'Letter Frequency in {language}')
    plt.show()


def menu():
    q = ""
    while q != "q":
      print("choose an option (q to quit)")
      print("1. spanish")
      print("2. polish")
      print("3. english")
      q = input()
      if q == "1":
        with open("spanish.txt", "r", encoding="utf-8") as f:
            text_es = f.read()
        result_es, letters_es= getFreq(text_es)

        print("---------------------spanish----------------")

        for char in letters_es:
            print("%5s %5f" %(char, (100* result_es[char]/ len(text_es)))+ "%")
        plot_letter_frequency(result_es, letters_es, "Spanish", len(text_es))
      elif q == "2":
        with open("polish.txt", "r", encoding="utf-8") as f:
            text_pl = f.read()
        result_pl, letters_pl= getFreq(text_pl)

        print("---------------------polish--------------------")

        for char in letters_pl:
            print("%5s %5f" %(char, (100* result_pl[char]/ len(text_pl))) + "%")
        plot_letter_frequency(result_pl, letters_pl, "Polish", len(text_pl))
      elif q == "3":
        with open("english.txt", "r", encoding="utf-8") as f:
            text_en = f.read()
        result_en, letters_en= getFreq(text_en)

        print("---------------------english----------------")

        for char in letters_en:
            print("%5s %5f" %(char, (100*result_en[char]/ len(text_en)))+ "%")
        plot_letter_frequency(result_en, letters_en, "English", len(text_en))




menu()