# -*- coding: utf-8 -*-
"""nba_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XyVnt5kV77ywOiXWbU3hFXKqtVfmmRmc
"""

import pandas as pd
import matplotlib.pyplot as plt

bball = pd.read_csv('all_seasons.csv')
bball.info()
#bball.last_name.unique()
#bball.points.mean()
#bball.head(50)
#pts_sorted = bball.sort_values(by='reb', ascending=False)
#pts_sorted.head(50)

import pandas as pd
import matplotlib.pyplot as plt

bball = pd.read_csv('all_seasons.csv')
bball_unique_players = bball.drop_duplicates(subset=['player_name'])
college_counts = bball_unique_players['college'].value_counts()
college_counts = college_counts[college_counts > 10]

plt.figure(figsize=(12, 8))
college_counts.plot(kind='bar')
plt.title('Número de jugadores por universidad', fontsize=16)
plt.xlabel('Universidad', fontsize=14)
plt.ylabel('Número de jugadores', fontsize=14)

"""QUick graph to show that the best universities (Duke, UCLA, Kentucky) that win the most, end up with the most players in the nba"""

import pandas as pd
import matplotlib.pyplot as plt

bball = pd.read_csv('all_seasons.csv')

bball_unique_players = bball.drop_duplicates(subset='player_name')

plt.figure(figsize=(10, 6))
plt.scatter(bball_unique_players['player_height'], bball_unique_players['reb'], alpha=0.7)

plt.title('Rebounds per Game vs Player Height', fontsize=16)
plt.xlabel('Player Height (cm)', fontsize=14)
plt.ylabel('Rebounds per Game', fontsize=14)

plt.show()

"""In this graph we can check the correlation between height and grabbing rebounds. There is a clear correlation, as in the taller you are, the more rebounds you are grabbing, but there are clear exceptions, like Dennis Rodman who at 198 cm has the highest rebound per game stat in the dataset."""

import pandas as pd
import matplotlib.pyplot as plt

bball = pd.read_csv('all_seasons.csv')

bball_unique_players = bball.drop_duplicates(subset='player_name')

plt.figure(figsize=(10, 6))
plt.scatter(bball_unique_players['player_height'], bball_unique_players['ast'], alpha=0.7)

plt.title('Assists per Game vs Player Height', fontsize=16)
plt.xlabel('Player Height (cm)', fontsize=14)
plt.ylabel('Assist per Game', fontsize=14)

plt.show()

"""Now we can check the correlation between player height and assists per game. We can see that it is inversely proportional. It seems that the bigger the player, the less assists they get. This is because smaller players are in charge of controlling the offense and passing."""

import pandas as pd
import matplotlib.pyplot as plt

bball = pd.read_csv('all_seasons.csv')

ts_avg_per_season = bball.groupby('season')['ts_pct'].mean()

plt.figure(figsize=(12, 6))
ts_avg_per_season.plot(kind='line', marker='o', color='b', linestyle='-', linewidth=2)

plt.title('Evolution of True Shooting Average by season', fontsize=16)
plt.xlabel('Season', fontsize=14)
plt.ylabel('True Shooting Average (TS%)', fontsize=14)

plt.show()

"""True shooting is a statistic that takes all shots a player takes, wheighs their value (1/2/3 points) and tells you how efficient that player is. In this graph, we can see that average true shooting has been going up season by season, as players get better and the game evolves."""