# -*- coding: utf-8 -*-
"""Movie_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_ptoSE26_bIGXQsS-Hh5ixz4QNDHGsQe
"""

import pandas as pd
import matplotlib.pyplot as plt
from collections import Counter

df = pd.read_csv("imdb_top_1000.csv")

df['Gross'] = df['Gross'].replace(',', '', regex=True).astype(float)

plt.scatter(df["IMDB_Rating"], df["Gross"])
plt.xlabel("Rating")
plt.ylabel("Money made by film")
plt.title("IMDB Rating vs Money made")
plt.show()

top_5_imdb = df[['Series_Title', 'IMDB_Rating']].sort_values(by='IMDB_Rating', ascending=False).head(5)

top_5_gross = df[['Series_Title', 'Gross']].sort_values(by='Gross', ascending=False).head(5)

plt.barh(top_5_imdb['Series_Title'], top_5_imdb['IMDB_Rating'])
plt.title('Top 5 IMDb rated films')
plt.xlabel('IMDB rating')
plt.ylabel('title')
plt.show()

plt.barh(top_5_gross['Series_Title'], top_5_gross['Gross'])
plt.title('Top 5 films by money earned')
plt.xlabel('money earned')
plt.ylabel('title')
plt.show()

"""Here I compare money made by a film with the score it obtained. As we can see there isnt a correlation between film score and money made, which i didnt expect. But this csv file takes the 1000 films with the best score, so maybe if it included all films we woud see a correlation.
Also out of curiosity I wanted to check which were some of the movies on the graph, the ones which made the most money and the ones that are best rated. As you can see, shawshank redemption is the highest rated film but didnt earn much money.
"""

import pandas as pd
import matplotlib.pyplot as plt
from collections import Counter

df = pd.read_csv("imdb_top_1000.csv")

top_directors= df['Director'].value_counts().head(10)
plt.barh(top_directors.index, top_directors.values)
plt.xlabel("Number of movies")
plt.ylabel("Director")
plt.title("Top 10 Directors by number of movies in the top 1000")
plt.show()

"""So in this graph i thought it would be interesting to see which directors have the most movies in the top 1000."""